Vagrant.configure("2") do |config|
  config.vm.box = "fedora/27-cloud-base"
  config.vm.box_check_update = false
  config.vm.synced_folder '.', '/vagrant', :nfs => true, :nfs_version => 4, :nfs_udp => false
  config.vm.synced_folder "/home/kent", "/home/kent", :nfs => true, :nfs_version => 4, :nfs_udp => false
  config.vm.synced_folder "/home/coredump", "/home/coredump", :nfs => true, :nfs_version => 4, :nfs_udp => false

  config.vm.provision :shell, path: "../scripts/fedora-init.sh"
  config.vm.provision :shell, path: "../scripts/increase_swap.sh"

  config.vm.define "dev1" do |dev1|
    dev1.vm.hostname = 'master'
    dev1.vm.network "private_network", ip: "192.168.88.30"
    dev1.vm.provider :libvirt do |v|
      v.memory = 1024
      v.cpus = 2
    end
  end

  config.vm.define "dev2" do |dev2|
    dev2.vm.hostname = 'cache1'
    dev2.vm.network "private_network", ip: "192.168.88.20"
    dev2.vm.provider :libvirt do |v|
      v.memory = 1024
      v.cpus = 4
    end
  end

end
