Vagrant.configure("2") do |config|
  config.vm.box = "fedora/23-cloud-base"
  config.vm.box_check_update = false
  config.vm.synced_folder '..', '/vagrant', type: "virtualbox"
  config.vm.synced_folder "D:/", "/data"
  config.vm.provision :shell, path: "../scripts/fedora-init.sh"
  config.vm.provision :shell, path: "../scripts/increase_swap.sh"
  
  config.vm.provider :virtualbox do |vb|
    vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate","1"]
  end

  config.vm.define "master" do |master|
    master.vm.hostname = 'master'
    master.vm.network "private_network", ip: "192.168.88.100"
    master.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 2
    end
  end

  config.vm.define "cache1" do |cache1|
    cache1.vm.hostname = 'cache1'
    cache1.vm.network "private_network", ip: "192.168.88.101"
    cache1.vm.provider "virtualbox" do |v|
      v.memory = 6144
      v.cpus = 4
    end
  end

  config.vm.define "cache2" do |cache2|
    cache2.vm.hostname = 'cache2'
    cache2.vm.network "private_network", ip: "192.168.88.102"
    cache2.vm.provider "virtualbox" do |v|
      v.memory = 1024
      v.cpus = 2
    end
  end
end