Vagrant.configure("2") do |config|
  config.vm.box = "fedora/23-cloud-base"
  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "192.168.88.101"
  config.vm.synced_folder "D:", "/data"
  config.vm.synced_folder ".", "/vagrant", type:"virtualbox"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  end
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
end
