Vagrant.configure("2") do |config|
  config.vm.box = "fedora/26-cloud-base"
  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "192.168.88.60"
  config.vm.synced_folder '..', '/vagrant', type: "virtualbox"
  config.vm.synced_folder "D:/", "/data"
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 1
  end

  config.vm.provision :shell, path: "../scripts/fedora-init.sh"
  config.vm.provision :shell, path: "../scripts/increase_swap.sh"
end