Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "192.168.88.61"
  config.vm.synced_folder '..', '/vagrant', type: "virtualbox"
  config.vm.synced_folder "D:/", "/data"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = 8192
    vb.cpus = 4
  end

  config.vm.provision :shell, path: "../scripts/ubuntu-init.sh"
  config.vm.provision :shell, path: "../scripts/increase_swap.sh"
end
