Vagrant.configure("2") do |config|
  config.vm.box = "fedora/27-cloud-base"
  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "192.168.88.70"
  config.vm.synced_folder '.', '/vagrant', :nfs => true, :nfs_version => 4, :nfs_udp => false
  config.vm.synced_folder "/home/kent", "/home/kent", :nfs => true, :nfs_version => 4, :nfs_udp => false
  config.vm.provider :libvirt do |libvirt|
    libvirt.cpus = 1
    libvirt.memory = 1024
  end

  config.vm.provision :shell, path: "../scripts/fedora-init.sh"
  config.vm.provision :shell, path: "../scripts/increase_swap.sh"
end
